### ISSUE TITLE
Electrodes

### ISSUE THREAD

**Issue by Nivek92** [UlysseCoteAllard/3DC-Armband#1]
What kind of electrodes do you use for this?

In the paper it only says "standard electrode".

**Comment by UlysseCoteAllard** [comment]
Electroless nickel immersion gold (ENIG) (in Table 1)

**Comment by Nivek92** [comment]
Ok I just saw the PCB for the electrodes. Thanks.

**Comment by UlysseCoteAllard** [comment]
Glad that was helpful. Don't hesitate if you have another question. 

Have a great day!
